SQL server support in Retriever component

diff --git a/comps/retrievers/src/Dockerfile b/comps/retrievers/src/Dockerfile
--- a/comps/retrievers/src/Dockerfile
+++ b/comps/retrievers/src/Dockerfile
@@ -13,6 +13,27 @@ RUN apt-get update -y && apt-get install -y --no-install-recommends --fix-missin
     libmariadb-dev \
     build-essential
 
+# # Check Debian version and fail if unsupported
+# RUN DEBIAN_VERSION=$(grep VERSION_ID /etc/os-release | cut -d '"' -f 2 | cut -d '.' -f 1) && \
+#     if ! echo "11 12" | grep -qw "$DEBIAN_VERSION"; then \
+#         echo "Debian $DEBIAN_VERSION is not currently supported." && exit 1; \
+#     fi
+
+# Add Microsoft package repo
+RUN DEBIAN_VERSION=$(grep VERSION_ID /etc/os-release | cut -d '"' -f 2 | cut -d '.' -f 1) && \
+    curl -sSL -O https://packages.microsoft.com/config/debian/$DEBIAN_VERSION/packages-microsoft-prod.deb && \
+    dpkg -i packages-microsoft-prod.deb && \
+    rm packages-microsoft-prod.deb
+
+# Install Microsoft ODBC Driver and tools
+RUN apt-get update && \
+    ACCEPT_EULA=Y apt-get install -y \
+    msodbcsql18 \
+    mssql-tools18 \
+    unixodbc-dev \
+    libgssapi-krb5-2 && \
+    echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
+
 RUN useradd -m -s /bin/bash user && \
     mkdir -p /home/user && \
     chown -R user /home/user/
